scenario:
  name: bologna_car1_custom
map:
  place_name: Bologna, Emilia-Romagna, Italy
  place_slug: Bologna_Emilia-Romagna_Italy
  map_scenario: nodes_80
  graphml_path: C:\Users\eielp\OneDrive\Desktop\UNICAL\AUTOMATED PLANNING\routly-planner\data\Bologna_Emilia-Romagna_Italy\nodes_80\road_network.graphml
  mapping_path: C:\Users\eielp\OneDrive\Desktop\UNICAL\AUTOMATED PLANNING\routly-planner\data\Bologna_Emilia-Romagna_Italy\nodes_80\roads_mapping.json
vehicles:
- id: car1
  start:
    type: location_id
    value: loc_0064
    x: 685960.641
    y: 4929567.718
  goal:
    type: location_id
    value: loc_0014
    x: 686784.431
    y: 4929329.656
