scenario:
  name: bologna_car1_custom
map:
  place_name: Bologna, Emilia-Romagna, Italy
  place_slug: Bologna_Emilia-Romagna_Italy
  map_scenario: nodes_80
  graphml_path: C:\Users\eielp\OneDrive\Desktop\UNICAL\AUTOMATED PLANNING\routly-planner\data\Bologna_Emilia-Romagna_Italy\nodes_80\road_network.graphml
  mapping_path: C:\Users\eielp\OneDrive\Desktop\UNICAL\AUTOMATED PLANNING\routly-planner\data\Bologna_Emilia-Romagna_Italy\nodes_80\roads_mapping.json
vehicles:
- id: car1
  start:
    type: location_id
    value: loc_0002
    x: 685856.646
    y: 4929585.13
  goal:
    type: location_id
    value: loc_0023
    x: 686472.355
    y: 4929463.923
