scenario:
  name: bologna_car1_custom
map:
  place_name: Bologna, Emilia-Romagna, Italy
  place_slug: Bologna_Emilia-Romagna_Italy
  map_scenario: nodes_100
  graphml_path: data\Bologna_Emilia-Romagna_Italy\nodes_100\road_network.graphml
  mapping_path: data\Bologna_Emilia-Romagna_Italy\nodes_100\roads_mapping.json
vehicles:
- id: car1
  start:
    type: location_id
    value: loc_0002
    x: 685802.501
    y: 4929602.002
  goal:
    type: location_id
    value: loc_0019
    x: 686784.431
    y: 4929329.656
