scenario:
  name: "car1_center_to_far"

map:
  place_name: "Bologna, Emilia-Romagna, Italy"
  map_scenario: "nodes_80"

vehicles:
  - id: "car1"
    start:
      type: "city_center"
    goal:
      type: "furthest_reachable"

      