osm:
  place_name: "Ravenna, Emilia-Romagna, Italy"
  network_type: "drive" # up to now only drive 

area:
  center_latitude: 44.4949
  center_longitude: 11.3426
  distance_meters: 1200

graph_simplification:
  keep_largest_component: true
  remove_isolated_nodes: true
  max_nodes_for_pddl: 80
  max_edges_for_pddl: 150


