features:
  traffic_lights: true # true | false

  congestion:
    mode: "pddl" # "none" | "sumo_only" | "pddl"
    num_background_vehicles: 200   # only if mode is not "none"
    congestion_factor: 2.0     # speed / congestion_factor on congested roads (only if mode: "pddl")
    congested_fraction: 0.2    # top 20% most central roads are congested (only if mode: "pddl")

  llm_events:
    enabled: true