osm:
  place_name: "Bologna, Emilia-Romagna, Italy"
  network_type: "drive" 


graph_simplification:
  keep_largest_component: false
  remove_isolated_nodes: true
  distance_meters : 2000
  max_nodes : 80

